# Doctrine Configuration
doctrine:
    dbal:
        driver:      %database_driver%
        unix_socket: %database_socket%
        host:        %database_host%
        port:        %database_port%
        dbname:      %database_name%
        user:        %database_user%
        password:    %database_password%
        charset:     UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

doctrine_mongodb:
    connections:
        mongo:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: hermes
    document_managers:
        mongo:
            auto_mapping: true
