parameters:
#    frequence_web_hermes.example.class: FrequenceWeb\Bundle\HermesBundle\Example

services:
#    frequence_web_hermes.example:
#        class: %frequence_web_hermes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
